#cloud-config inline bash
write_files:
- path: /home/startup.sh
    content: |
    #!/bin/bash
    # update ubuntu
    set -ex \
    && sudo apt-get update -y \
    && sudo apt-get install software-properties-common \
    && sudo apt-get update -y \
    && sudo apt-get install -y apt-transport-https wget unzip jq git \
    && sudo wget https://releases.hashicorp.com/terraform/${terraformVersion}/terraform_${terraformVersion}_linux_amd64.zip \
    && sudo unzip ./terraform_${terraformVersion}_linux_amd64.zip -d /usr/local/bin/ \
    && terraform -install-autocomplete \
    ### install awscli \
    && sudo apt-get install awscli -y
runcmd:
- ["sh", "/home/startup.sh"]

# built in
#cloud-config
# packages:
#   - nginx
# package_update: true
# runcmd:
#   - [systemctl, daemon-reload]
#   - [systemctl, enable, nginx]
#   - [systemctl, start, nginx]

# /var/log/cloud-init.log